### ISSUE TITLE
question about the initial method in the cct

### ISSUE THREAD

**Issue by knightyxp** [microsoft/VideoX#69]
Hey bolin:
        I notice the initialize in xclip is special, especially IFA(intra-frame diffusion attention)inherits the weights directly from the pretrained models.while the CFA is is randomly initialized. However, in the code of CCT, I do not find the implementation of such initial method, it seems like just is is the normal initial

**Comment by nbl97** [comment]
Thanks for your interest~
The randomly initialized parts are initialized using [this line](https://github.com/microsoft/VideoX/blob/master/X-CLIP/models/xclip.py#L81), and the inherited parts are using [this line](https://github.com/microsoft/VideoX/blob/master/X-CLIP/models/xclip.py#L189). Note that we have specifically kept the inherited parts sharing the same variable name of CLIP so that it can be inherited directly.

**Comment by nbl97** [comment]
Oh, I see your questions. The initialization of CFA can be found [here](https://github.com/microsoft/VideoX/blob/master/X-CLIP/models/cct.py#L99). The variables starting without "message_" will then inherit the CLIP pretrained parameters, and only the variables starting with "messge_" are randomly initialized.
Hope it can help you.

**Comment by knightyxp** [comment]
actually,  https://github.com/microsoft/VideoX/blob/ff43d7400af16f4db2cd884ff0512fbb0b581cc3/X-CLIP/models/cct.py#L99 will only initial the text encoder parameters as followed image illustrated, containing token embedding, positional embedding and self.transformer blocks(all for encode text)
![image](https://user-images.githubusercontent.com/48432506/194762038-05e6b75f-1f9b-4a15-a747-d703e68d491c.png)

but in the video encoder, there do not have initial code, only in each module like cct and mit, however, cct would not initial the parameter since 'self. apply(self._init_weights)' is not in the def__init__ function.
![image](https://user-images.githubusercontent.com/48432506/194762029-fd075a98-ba22-4b42-9215-e755ade4028e.png)
![Uploading image.png…]()
any way， even when I figure all problems out in my work( try your video-specific prompt in text-to-video retrieval), it still does not work, but the naive temporal model still works...

**Comment by nbl97** [comment]
Thanks for pointing out `self.apply(self.init_weights)' is not in the def__init_ function`. We will clean the code. But I think this does not affect performance and initialization, because each operation (e.g., nn.MultiheadAttention, nn.Linear) in Pytorch has its own built-in and default initialization. 
I have not tried the text-to-video retrieval task. According to my intuitive understanding, maybe it needs more careful hyperparameter tuning. For example, the sentences of the retrieval task are more complex and perhaps need more layers to extract the information.
Hope this can help you.

**Comment by nbl97** [comment]
I'm closing this issue and pls feel free to ping me if there are further questions.
