### ISSUE TITLE
Train/Val list setting for Kinetics dataset

### ISSUE THREAD

**Issue by ychencq** [microsoft/VideoX#74]
Hi,
Appreciate your excellent work and impressive contribution to this area! 
I was doing some experiments in this field, too. However, Kinetics datasets are varied due to different methods of downloading and internet issues. As a great and solid job, I want to follow your setting on fully supervised experiments.
Could you share your train/val list with me? Thanks a lot in advance!

**Comment by nbl97** [comment]
Thanks for your appreciation, and sorry for the late reply.
You can find the train/val list of K400 [here](https://github.com/nbl97/X-CLIP_Model_Zoo/releases/download/v1.0/k400_list.zip). For K600, we download the data from [CVDF](https://github.com/cvdfoundation/kinetics-dataset) and use the provided file list. I know your point, but I don't think the missing data caused by the internet issues affects the results. So pls feel free to use the available and easy-to-use resources, such as CVDF.
Hope this can help you~
